### ISSUE TITLE
Midi Output in VST3 is not being passed to output.

### ISSUE THREAD

**Issue by DavidsonAudioMulti** [getdunne/modmate#1]
Midi Output in VST3 is not being passed to output. I tried the VST2 & VST3 version of modmate and the midi output is not working correctly in the VST3 plugin versions. I also tried the instrument version of the plugin and it was also not coming through there.

**Comment by getdunne** [comment]
ModMate was built with JUCE 5.4.x, where this was a known issue. I believe it has been corrected in JUCE 6. I will be rebuilding ModMate and ShowMIDI with JUCE 6 and will make a point of testing the VST3 versions.
